package main

// typeMap mirrors the switch_dict in parser.py's map_type().
var typeMap = map[string]string{
	"plg::string":              "string",
	"plg::vector<plg::string>": "string[]",
	"plg::str":                 "string",
	"plg::any":                 "any",
	"plg::vector<plg::any>":    "any[]",

	"void":               "void",
	"bool":               "bool",
	"float":              "float",
	"double":             "double",
	"void*":              "ptr64",
	"uintptr_t":          "ptr64",
	"intptr_t":           "ptr64",
	"char":               "char8",
	"signed char":        "char8",
	"char16_t":           "char16",
	"int8_t":             "int8",
	"int8":               "int8",
	"int16_t":            "int16",
	"int16":              "int16",
	"short":              "int16",
	"int32_t":            "int32",
	"int32":              "int32",
	"int":                "int32",
	"long":               "int32",
	"int64_t":            "int64",
	"int64":              "int64",
	"__int64":            "int64",
	"long long":          "int64",
	"uint8_t":            "uint8",
	"uint8":              "uint8",
	"unsigned char":      "uint8",
	"byte":               "uint8",
	"uint16_t":           "uint16",
	"uint16":             "uint16",
	"unsigned short":     "uint16",
	"uint32_t":           "uint32",
	"uint32":             "uint32",
	"unsigned int":       "uint32",
	"unsigned long":      "uint32",
	"uint64_t":           "uint64",
	"uint64":             "uint64",
	"unsigned __int64":   "uint64",
	"unsigned long long": "uint64",

	"plg::vector<bool>":               "bool[]",
	"plg::vector<float>":              "float[]",
	"plg::vector<double>":             "double[]",
	"plg::vector<void*>":              "ptr64[]",
	"plg::vector<char16_t>":           "char16[]",
	"plg::vector<int8_t>":             "int8[]",
	"plg::vector<int8>":               "int8[]",
	"plg::vector<int16_t>":            "int16[]",
	"plg::vector<int16>":              "int16[]",
	"plg::vector<short>":              "int16[]",
	"plg::vector<int32_t>":            "int32[]",
	"plg::vector<int32>":              "int32[]",
	"plg::vector<int>":                "int32[]",
	"plg::vector<long>":               "int32[]",
	"plg::vector<int64_t>":            "int64[]",
	"plg::vector<int64>":              "int64[]",
	"plg::vector<__int64>":            "int64[]",
	"plg::vector<long long>":          "int64[]",
	"plg::vector<uint8_t>":            "uint8[]",
	"plg::vector<uint8>":              "uint8[]",
	"plg::vector<unsigned char>":      "uint8[]",
	"plg::vector<byte>":               "uint8[]",
	"plg::vector<uint16_t>":           "uint16[]",
	"plg::vector<uint16>":             "uint16[]",
	"plg::vector<unsigned short>":     "uint16[]",
	"plg::vector<uint32_t>":           "uint32[]",
	"plg::vector<uint32>":             "uint32[]",
	"plg::vector<unsigned int>":       "uint32[]",
	"plg::vector<unsigned long>":      "uint32[]",
	"plg::vector<uint64_t>":           "uint64[]",
	"plg::vector<uint64>":             "uint64[]",
	"plg::vector<unsigned __int64>":   "uint64[]",
	"plg::vector<unsigned long long>": "uint64[]",

	"plg::vector<plg::vec3>": "vec3[]",
	"plg::vector<vec3>":      "vec3[]",
	"plg::vector<Vector>":    "vec3[]",
	"plg::vector<QAngle>":    "vec3[]",
	"plg::vector<Vector3D>":  "vec3[]",
	"plg::vector<Vector3>":   "vec3[]",
	"plg::vector<Vector3f>":  "vec3[]",

	"plg::vector<plg::vec2>": "vec2[]",
	"plg::vector<Vector2f>":  "vec2[]",
	"plg::vector<Vector2>":   "vec2[]",
	"plg::vector<Vector2D>":  "vec2[]",
	"plg::vector<vec2>":      "vec2[]",

	"plg::vector<plg::vec4>": "vec4[]",
	"plg::vector<Vector4>":   "vec4[]",
	"plg::vector<Vector4f>":  "vec4[]",
	"plg::vector<Vector4D>":  "vec4[]",
	"plg::vector<vec4>":      "vec4[]",

	"plg::vector<plg::mat4x4>": "mat4x4[]",
	"plg::vector<Matrix>":      "mat4x4[]",
	"plg::vector<Matrix4x4>":   "mat4x4[]",
	"plg::vector<mat4x4>":      "mat4x4[]",

	"CPlayerSlot":               "int32",
	"CEntityHandle":             "int32",
	"Handle":                    "uint64",
	"ConVarHandle":              "uint64",
	"plg::vector<ConVarHandle>": "uint64[]",

	"plg::vec3": "vec3",
	"vec3":      "vec3",
	"Vector":    "vec3",
	"QAngle":    "vec3",
	"Vector3D":  "vec3",
	"Vector3":   "vec3",
	"Vector3f":  "vec3",

	"Vector2D":  "vec2",
	"plg::vec2": "vec2",
	"vec2":      "vec2",
	"Vector2":   "vec2",
	"Vector2f":  "vec2",

	"Vector4D":   "vec4",
	"plg::vec4":  "vec4",
	"vec4":       "vec4",
	"Vector4":    "vec4",
	"Vector4f":   "vec4",
	"Quaternion": "vec4",

	"plg::mat4x4": "mat4x4",
	"Matrix":      "mat4x4",
	"Matrix4x4":   "mat4x4",
	"mat4x4":      "mat4x4",
}

// mapType maps a C++ type to a more user-friendly format.
func mapType(t string) string {
	if v, ok := typeMap[t]; ok {
		return v
	}
	return "?"
}
